### ISSUE TITLE
Ambiguity in exogenous_availability_scenario_id subscenario

### ISSUE THREAD

**Issue by sriharid** [blue-marble/gridpath#1074]
exogenous_availability_scenario_id refers to exogenous availability of both generation and transmission, causing ambiguity, and results in errors when availability inputs are imported from csvs to database for both generation and transmission

**Comment by anamileva** [comment]
@sriharid, could you expand a bit on why this is happening? I haven't seen this problem. The column name is indeed the same in the two tables, but I don't see a reason that there should be confusion as long as the port script is pointed to the CSV directories and the right tables including correctly identifying the inputs as "project_inputs" and "project_is_tx" in the respective columns. I need to understand exactly what the issue is before I attempting to fix it.

**Comment by sriharid** [comment]
@anamileva , somehow did not see your response earlier.

The issue I reported was based on an older version.

However, there is still an issue with updating the database using the port_csvs_to_db script. I have submitted a pull request for this issue: https://github.com/blue-marble/gridpath/pull/1085
