### ISSUE TITLE
OSError in running examples 

### ISSUE THREAD

**Issue by varunjyothiprakash** [blue-marble/gridpath#1082]
<img width="866" alt="Gridpath Example " src="https://github.com/blue-marble/gridpath/assets/69641248/3c68e6ed-3f67-4fbd-b737-36ce987d5a9c">
I request you please help me in debugging this OSError. I am running the test scenario in the example folder, but I am facing the error OSError: Scenario '../examples/test' does not exist. Please verify scenario name and scenario location. I have installed GP as per the instructions by Cd it to the root folder.

**Comment by sriharid** [comment]
Varun, 

Since this command is run in the root directory of the gridpath repository, you will need to specify the scenario_location as 'examples' (without the quotes).

Please use the Q&A section under the Discussions forum for posting questions about issues faced when learning gridpath. If an issue is discovered, you can always raise an issue in the Issues forum.

**Comment by varunjyothiprakash** [comment]
Dear Sir,

Thank you for your valuable inputs.
