### ISSUE TITLE
Difficulty using port_csvs_to_db.py to update subscenario

### ISSUE THREAD

**Issue by nmgeek** [blue-marble/gridpath#818]
Maybe I am going about this the wrong way, but it seemed like _port_csvs_to_db.py_ was the right utility to use to update my project portfolio subsenario.

1. It seems you need to add the -_-delete_ flag to _port_csvs_to_db.py_ in order to update a subsenario.  Without it, you get this error:

    `UNIQUE constraint failed: subscenarios_project_portfolios.project_portfolio_scenario_id`

2. The _--delete_ flag is ignored unless you include the _--subscenario_ and _--subscenario_id_ parameters.  (This is not documented in the help message.)
3. By trial and error I learned that the value you must provide for _--subscenario_ is the name of the subscenario id column, _project_portfolio_scenario_id_ in my case, rather than a simple subscenario name (this disagrees with help documentation).

**Comment by nmgeek** [comment]
As I build up my db I have found that various other things go wrong, including errors which leave the db locked.  So I have started deleting the db file and building the db from scratch each time I change a subscenario.  This approach is working pretty well so far.

**Comment by anamileva** [comment]
Yes, that's the correct way to update a subscenario using the port script. We have an open issue for improving the documentation around the csv-to-db functionality (#588). We'd love contributions.

Locking the database can happen but it should be rare and you shouldn't have to resort to rebuilding the whole thing. See here for some suggestions for how unlock it: https://stackoverflow.com/questions/151026/how-do-i-unlock-a-sqlite-database. I find that just opening it in DB Browser for SQLite or SQLite studio will generally be enough to unlock it.

**Comment by milindsmart** [comment]
I have also been tripped up by the expectation that `subscenario` requires me to type in, say, `temporal_scenario_id` rather than `temporal` or even `temporal_scenario`: the current wording makes one think of having to type in the `subscenario_id` of that particular subscenario, instead. 

All subscenarios except `solver_options_id` end in `_scenario_id`, and the names are probably better without this suffix. `solver_options_id` can become `solver_options`. 

FWIW, `subscenario` itself might be much clearer if renamed to `subscenario_dataset` or something like that. I understand it would result in sweeping changes throughout.
